---
abstract: 'lazily calculate the tuples of a cartesian-product'
author:
  - 'Stephen R. Scaffidi <sscaffidi@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300018, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Set-CartesianProduct-Lazy
requires:
  Carp: 0
  Data::Dumper: 0
  List::Util: 0
  Scalar::Util: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/Hercynium/Set-CartesianProduct-Lazy
  repository: https://github.com/Hercynium/Set-CartesianProduct-Lazy.git
version: 0.002
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::FakeRelease
      name: FakeRelease
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: Git::GatherDir
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/MakeMaker'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/Check'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/Tag'
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: CopyFilesFromBuild
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::ChangelogFromGit
      name: ChangelogFromGit
      version: 0.005
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 1.121010
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: ModuleBuild
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::PkgDist
      name: PkgDist
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::PodVersion
      name: PodVersion
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: 0.28
    -
      class: Dist::Zilla::Plugin::ReadmeMarkdownFromPod
      name: ReadmeMarkdownFromPod
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: ArchiveRelease
      version: 4.00
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300018
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300018
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300018
